always_for_in = true
remove_extra_newlines = true
always_use_return = true
format_docstrings = false
align_assignment = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
ignore = "docs/src/demos"